workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    triggering:
      events:
        - push
        - pull_request
    cache:
      cache_paths:
        - $HOME/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS app (unsigned for AltStore)
        script: |
          # 使用 flutter build ipa 命令
          flutter build ipa \
            --release \
            --no-codesign \
            --verbose

          # 查找生成的 .ipa 文件
          find . -name "*.ipa" -type f -exec ls -la {} \;
    artifacts:
      - build/ios/iphoneos/*.ipa
