workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    triggering:
      events:
        - push
        - pull_request
    cache:
      cache_paths:
        - $HOME/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS app (unsigned for AltStore)
        script: |
          # 构建 iOS Release 版本
          flutter build ipa --release --no-codesign

          # 列出构建产物
          find build -name "*.ipa" -type f
    artifacts:
      - build/ios/iphoneos/*.ipa
