workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
      os: macos_mini_m2
      flutter: stable
    triggering:
      events:
        - push
        - pull_request
    cache:
      cache_paths:
        - ~/.pub-cache
    steps:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ipa --release \
            --no-codesign \
            --dart-define=FLUTTER_APP_NAME=LocationTapper
        artifacts:
          - build/ios/iphoneos/*.ipa
