workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: true
    triggering:
      events:
        - push
        - pull_request
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/flutter
        - $HOME/Library/Developer/Xcode/DerivedData
    scripts:
      - name: Clean and prepare
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks
          flutter pub get
          flutter precache ios
      - name: Initialize iOS
        script: |
          flutter create . --platforms ios
          flutter pub get
      - name: Build iOS app
        script: |
          cd ios
          pod install --repo-update
          cd ..
          flutter build ios --no-codesign
      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/archive/Runner.xcarchive
