workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    triggering:
      events:
        - push
        - pull_request
    cache:
      cache_paths:
        - $HOME/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS app (unsigned for AltStore)
        script: |
          # 构建 iOS Release 版本
          flutter build ios --release --no-codesign

          # 复制构建产物到 ipa 目录
          mkdir -p build/ios/iphoneos/Payload
          cp -r build/ios/ios/Runner.app build/ios/iphoneos/Payload/

          # 创建 .ipa
          cd build/ios/iphoneos
          zip -r ../iphoneos.ipa Payload
          cd ../..

          ls -la build/ios/
    artifacts:
      - build/ios/*.ipa
