workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    triggering:
      events:
        - push
        - pull_request
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/flutter
        - $HOME/Library/Developer/Xcode/DerivedData
    scripts:
      - name: Clean and prepare
        script: |
          flutter clean
          flutter pub get
          flutter precache ios
          rm -rf ios/Pods ios/Podfile.lock
      - name: Build iOS app (unsigned for AltStore)
        script: |
          flutter build ios --no-codesign
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
