workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    triggering:
      events:
        - push
        - pull_request
    cache:
      cache_paths:
        - $HOME/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS app using xcodebuild
        script: |
          cd ios

          # 列出 project 中的 scheme
          echo "Schemes in project:"
          xcodebuild -project Runner.xcodeproj -list

          # 构建 app（无签名）
          xcodebuild \
            -project Runner.xcodeproj \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            clean build

          # 导出 .ipa
          xcodebuild \
            -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist Runner/ExportOptions.plist \
            -exportPath build/ipa \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          cd ..
          ls -la build/ipa/
    artifacts:
      - build/ipa/*.ipa
