workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    triggering:
      events:
        - push
        - pull_request
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/flutter
        - $HOME/Library/Developer/Xcode/DerivedData
    scripts:
      - name: Clean and prepare
        script: |
          flutter clean
          flutter pub get
          flutter precache ios
      - name: Regenerate iOS files
        script: |
          rm -rf ios/Flutter/flutter_export_environment.sh ios/Flutter/Generated.xcconfig ios/Flutter/Flutter.podspec
          flutter create . --platforms ios --overwrite
          ls -la ios/Flutter/
      - name: Build iOS app (unsigned for AltStore)
        script: |
          flutter build ios --no-codesign
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
