workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    triggering:
      events:
        - push
        - pull_request
    cache:
      cache_paths:
        - $HOME/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS app using xcodebuild
        script: |
          cd ios

          # 列出可用的 scheme
          echo "Available schemes:"
          xcrun xcodebuild -workspace Runner.xcworkspace -list

          # 获取 scheme 名称
          SCHEME=$(xcrun xcodebuild -workspace Runner.xcworkspace -list | grep "Runner" | head -1 | tr -d ' ')
          echo "Using scheme: $SCHEME"

          # 清理旧的构建
          xcodebuild clean -workspace Runner.xcworkspace -scheme "$SCHEME" -configuration Release 2>/dev/null || true

          # 构建 .ipa（无签名）
          xcodebuild archive \
            -workspace Runner.xcworkspace \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -skipPackagePluginValidation \
            -skipMacroValidation

          # 导出 .ipa
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist Runner/ExportOptions.plist \
            -exportPath ../build/ios/iphoneos \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          cd ..

          ls -la build/ios/iphoneos/
    artifacts:
      - build/ios/iphoneos/*.ipa
