#!/bin/bash
# Generated by Flutter

# Set default values
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FLUTTER_ROOT="${FLUTTER_ROOT:-$(dirname $(dirname $(which flutter)))}"
PROJECT_DIR="$(dirname $(dirname "$SCRIPT_DIR"))"
BUILT_PRODUCTS_DIR="${BUILT_PRODUCTS_DIR:-${PROJECT_DIR}/build/ios/Profile-iphoneos}"
UNOPTIMIZED_BUILT_PRODUCTS_DIR="${UNOPTIMIZED_BUILT_PRODUCTS_DIR:-${PROJECT_DIR}/build/ios/iphoneos}"

# Export environment variables
export FLUTTER_ROOT
export FLUTTER_APPLICATION_PATH="$PROJECT_DIR"
export PACKAGE_CONFIG="${PROJECT_DIR}/.dart_tool/package_config.json"
